### ISSUE TITLE
Memory Allocation Error

### ISSUE THREAD

**Issue by rhymyst** [weizhouUMICH/SAIGE#141] opened 2020-02-05 09:26 UTC
After updating SAIGE from 0.35.8.8 to 0.36.3,
I have got the memory allocation error in step2 (SAIGE-GENE),
"Error: cannot allocate vector of size 490.9 Gb"
Sample N is within 300k and marker N for GRM is 183,108.

Thank you.

**Comment by weizhouUMICH** [comment] 2020-02-06 17:22
The error message seems from R. Are you using the same input files for phenotypes?

**Comment by rhymyst** [comment] 2020-02-07 06:03
Thank you for your reply.
Yes, I used same phenotype files in 0.35.8.8 and 0.36.3.

As I see it, the error occurs between these lines in SAIGE_SKAT_quantitative.R.
66: cat("weights: ", weights, "\n")	
466: print(re)

**Comment by weizhouUMICH** [comment] 2020-02-07 15:27
Thanks! If the issue is from SAIGE_SKAT_quantitative.R (step 2),  phenotype file and and plink files are not needed in this step. How many variants are there in the tested gene? 
How large is the sparse GRM?

**Comment by weizhouUMICH** [comment] 2020-02-07 18:37
Could you please update the SKAT library by 
1. open R
2. devtools::install_github("leeshawn/SKAT")

The problem should be fixed then. 

The memory issue is caused by the SKATBinary function in the SKAT R library. The issue has been fixed by developers of SKAT and they are uploading the new version to CRAN. 
Before the new version of SKAT is available in CRAN, the library can be re-installed from the their github. Thanks!

**Comment by rhymyst** [comment] 2020-02-09 22:50
After updating SKAT, it works well.
Thank you very much for fixing it!

**Closed** 2020-02-22 04:04 UTC
